<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-70NPE6Q" failures="1" tests="7" name="Retry all failed Tests" time="0.18" errors="0" timestamp="06 Mar 2021 10:29:08 GMT">
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.03">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.006">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at AgainRetryTests.RetryTestsTransform.Test1(RetryTestsTransform.java:11)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="AgainRetryTests.RetryTestsTransform" name="Test2" time="0.002"/>
</testsuite> <!-- Retry all failed Tests -->
